# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Inline-TT
version:      0.04
version_from: lib/Inline/TT.pm
installdirs:  site
requires:
    Inline:                        0.42
    Template:                      2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
